### ISSUE TITLE
"ExpenseCard" component

### ISSUE THREAD

**Issue by luceroweb** [luceroweb/karot-saving-smart#10]
[timebox: 2-3 hours, complexity points: 2]

As a user, I want to see a card/tile that displays how much money I have left to spend on that expense.

**User Expectations:**

**Developer Dependencies**
- Figma Wireframe: https://www.figma.com/file/qgAYJmI9jnoocgKRfWarpb/Envelope-App?node-id=50%3A579

![expenseCard](https://user-images.githubusercontent.com/82012415/169912997-4d87bb7f-a872-401b-a464-d14e4660cfd0.png)
- Google Font: Sarabun: https://www.npmjs.com/package/@expo-google-fonts/sarabun
- following object as an input:
{
label: string;
saved: number;
goal: number;
date: Date;
}

**Comment by luceroweb** [comment]
@garanico @srosenberg74 I think this is about right. Could you please read through it again to confirm that my changes still make sense? If not, please continue to modify it.

**Comment by garanico** [comment]
@luceroweb I think this makes sense.  @srosenberg74 do you think anything else needs to be added?

**Comment by srosenberg74** [comment]
@luceroweb Hi Juan!  We are wondering if this ticket is just for the expense card that shows on the Overview Screen or if it is for the actual separate page that you go to when you click on the tile, or both

**Comment by luceroweb** [comment]
@srosenberg74 this ticket is just for the expense card that shows on the overview screen in a category tab. Not to Overview page, or the category tab, not even the list of expense cards, but just one individual card. This component  will be used to create the expense list in another ticket.
