### ISSUE TITLE
Bug: The ExpenseDetailView is wider than it's container in mobile and the add expense button should not be displayed while viewing the ExpenseDetails

### ISSUE THREAD

**Issue by srosenberg74** [luceroweb/karot-saving-smart#127]
Date Seen
7/8/22

Versions
Android emulator
Develop branch

Bug Description
In the Android emulator, the ExpenseDetailView is wider than the Budget Card container behind it.  Also, the add expense button is still visible and can be pressed while in the Expense Detail View.

Steps to Reproduce
1. Run project in the Android emulator
2. Add an expense
3. Click on the expense to open the Expense Detail View
4. Notice that the container of the Expense Details View/Modal is wider than the container behind it.
5. Notice that the add expense button is still displayed and can be interacted with even while the Expense Details View/Modal is open.

Actual Behavior
The container for the Expense Detail View is wider than the container behind it and the add expense button is still displayed and can be interacted with while viewing the Expense Detail View.

Expected Behavior
The container for the Expense Detail View will be the same width as the container behind it(Budget Card) and the add Expense button will not be accessible or displayed while viewing an expense's details.

Troubleshooting/Testing Steps Attempted
Not yet

Workaround
Not yet

**Comment by luceroweb** [comment]
https://github.com/luceroweb/karot-saving-smart/commit/99e4bc04d978b2a26d585c1d007d1985b8abd7a1
