### ISSUE TITLE
Change Login.js to Login.tsx and refactor code accordingly

### ISSUE THREAD

**Issue by srosenberg74** [luceroweb/karot-saving-smart#28]
[timebox: 1 hour, complexity: 2]

As a developer I need the Login.js file to be converted to a TypeScript document named Login.tsx and the code to be refactored to TypeScript so that it will align with the rest of the app.

**Developer Expectations:**
- Login.js will be a TypeScript file instead of a JavaScript file, and all necessary TypeScript type definitions will be added to the code

**Developer Dependencies:**
- May need to use ReduxStateTest.tsx and other component files as reference while making the transition to TypeScript.
- May need to pull type definitions from `Utils/types.ts`

**Comment by luceroweb** [comment]
@Hiwot-Beshe @eyobel7k @xmercado please work together to merge your changes that are in progress into the Login.tsx file.

**Comment by luceroweb** [comment]
Thank you @xmercado @Hiwot-Beshe @eyobel7k for completing this work in #11 . Closing ticket.
