### ISSUE TITLE
Plus Icon control to open "Account" modal

### ISSUE THREAD

**Issue by luceroweb** [luceroweb/karot-saving-smart#35]
**[timebox: 1 hour, complexity points: 2]**

As a user, in the Expense list section of the app, I would like to select a control so that the existing account form modal is displayed.

**User Expectations:**
- A plus icon control in the center, below the accounts list in the AccountsDropDown
- When you press the button it opens the add account form modal

**Developer Dependencies:**
- #7 
- Add a fixed position plus icon control in the center, below the accounts list in the AccountsDropDown
- When selected, display the existing account form modal from #7 
![image](https://user-images.githubusercontent.com/80865274/172728307-7d91973f-510e-40ce-9353-e9576417d72f.png)
![Screenshot from 2022-06-09 11-10-11](https://user-images.githubusercontent.com/10747669/172915581-cddcab94-d216-42f2-a349-c412e79347ca.png)

**Comment by luceroweb** [comment]
@keshi2021 @garetshough14 We modified this ticket to clarify that it is only about adding the plus icon control and onpress action to the expense list section.

**Comment by srosenberg74** [comment]
@keshi2021 @garetshough14 I have updated the ticket to reflect that the control/plus icon was placed in the AccountsDropDown instead of the bottom right of the Expense List.
