### ISSUE TITLE
Bug: Fix styling issues for Expense Card component in emulator

### ISSUE THREAD

**Issue by srosenberg74** [luceroweb/karot-saving-smart#37]
**Date Seen**
6/6/22

**Versions**
Android Emulator
Develop Branch

**Bug Description**
In the emulator, the Expense card renders incorrectly, taking up the full space of it's parent container and with some of the info displayed off screen.  The styling should match the Figma.

Expense Card in Figma:
![expensecard](https://user-images.githubusercontent.com/91571340/172275191-f1efdd43-bee1-40ac-82ad-48d5bfc71f6b.png)

Actual Expense Card in emulator now:
![expensecard2](https://user-images.githubusercontent.com/91571340/172275226-1abbcb3e-34ce-4dd1-a477-d5617c553c22.png)

**Steps to Reproduce**

1. Add a test data object into the list in initialState in expenseSlice.ts.  (for example:   {
      label: "Bank",
      saved: 1000,
      goal: 2000,
      date: Date.now(),
    })
2. Run the project on Android emulator.
3.  Note on the Overview Screen that the expense card is improperly formatted in the emulator when compared to the figma. 

**Actual Behavior**
The styling on for the Expense Card is incorrect in the emulator.

**Expected Behavior**
The styling for the Expense Card will more closely match the styling in the figma.

**Troubleshooting/Testing Steps Attempted**
Removing line 33 from ExpenseCard.tsx(`flex: 1`) should help solve this issue, however additional styling needs to be done to place all the contents in the correct locations. In addition, in order to format the amounts correctly to match the figma, toLocaleString() could be added to line 20 in ExpenseCard.tsx, like this: `<Text style={styles.expenseAmount}>${expense.saved.toLocaleString()}</Text>`

**Comment by xmercado** [comment]
@srosenberg74 I removed flex: 1 and it resolved most of the styling issues for android emulator. For the placement of individual cards, should that be handled in another ticket and component called something like ExpenseList instead?

**Comment by srosenberg74** [comment]
@xmercado Yes, the placement of the cards should be handled in another ticket.  When I tested just removing the flex: 1 it appeared that the content of the card was too close to the edge of the card, there didn't seem to be enough padding when used in the emulator, so I thought there might need to be some additional styling necessary for styling the content within the card.

**Comment by luceroweb** [comment]
@xmercado yes, the #30 ticket should resolve the list layout issue. I'll add a note to that ticket now.
cc @keshi2021 @garetshough14
