### ISSUE TITLE
Chore: Cleanup font imports

### ISSUE THREAD

**Issue by alberme** [luceroweb/karot-saving-smart#46]
[timebox: , complexity points: ]

As a developer, I would like to have Sarabun fonts preloaded and any other fonts replaced with Sarabun so that I don't have to repeat the same font loading on multiple components.

**Developer Expectations:**
* Search for unnecessary font imports in other components outside of the `SplashScreenAnimation` component
* Replace any font references other than Sarabun with the correct font
* Remove those unnecessary font imports as well as any usage of `useFonts` in components
  * Preloading fonts in `SplashScreenAnimation` should eliminate the need to import and load custom fonts in every component that requires it.

**Developer Dependencies**
- #16 
- https://docs.expo.dev/versions/latest/sdk/splash-screen/

**Comment by luceroweb** [comment]
@alberme I added a note to this ticket to also replace any references to non-Sarabun fonts with Sarabun to resolve loading errors in the Android emulator.
