### ISSUE TITLE
Alter Add Account Form to Accept "mode" prop

### ISSUE THREAD

**Issue by luceroweb** [luceroweb/karot-saving-smart#48]
[timebox: 1-2 hours, complexity: 2]

As a user, I would like to be able to edit my accounts using the account form so that I can update my existing accounts as needed.

As a developer, I need to modify the existing add account form  #7  so that when you pass in `mode='edit' account={[[the account you want to edit will be passed in here]]}`, the form is pre-filled with the selected account's data, and the `submit` button is labelled `update`.

**Developer Expectations**

- The existing Add Account Form(#7) will need to be modified. When edit mode is chosen, replace the 'Add to List' button with 'Update'.

![addaccount](https://user-images.githubusercontent.com/91571340/172735528-16305b13-15a9-4a23-ba90-5470a66aecc8.png)

**Developer Dependencies**

- The existing Add Account Form (#7) will receive a 'mode' property and also an 'account' property to determine whether it is in Add Account or edit account mode(ex: `mode='edit' account={accountToEdit}`)
- If the account 'mode' is edit, then an 'update' should appear in the form in place of 'Add to list'

**Comment by srosenberg74** [comment]
Oh shoot, I've noticed that the way I wrote this ticket there is a lot of redundancy with #42.  I will try to adjust it so that there isn't overlap
