### ISSUE TITLE
Bug: Default date for Expense Form Input

### ISSUE THREAD

**Issue by srosenberg74** [luceroweb/karot-saving-smart#58]
**Date Seen**
6/10/22

**Versions**
Android Emulator
Chrome Web Browser
Develop Branch

**Bug Description**
If no date is selected by the user in the form in the ExpenseModal.tsx then a date of 12/31/69 is set for the expense.

**Steps to Reproduce**

1. Start the app
2. Login
3. Click the plus sign at the bottom right of the screen
4. Add an expense using the form, but don't select a date, then submit
5. Observe that the Expense Card created lists the date as 12/31/69

**Actual Behavior**
If the user doesn't select a date in the expense card modal form, then the date 12/31/69 is automatically listed as the date of the expense.

**Expected Behavior**
Rather than having 12/31/69 as the default date, an error should let the user know that they need to select a date before the form can be submitted.

**Troubleshooting/Testing Steps Attempted**
None so far

**Comment by luceroweb** [comment]
@srosenberg74 @alberme consider setting the new expense date field value to today by default and allow the user to change that date.
