### ISSUE TITLE
Bug: error after adding an expense

### ISSUE THREAD

**Issue by garanico** [luceroweb/karot-saving-smart#60]
**Date Seen**
11:10am 6/10/22

**Versions**
Develop branch
Chrome

**Bug Description**
When you add an expense, the following error shows up: 
![173126152-4071d024-f79c-47f6-941b-9ec71f598e8e](https://user-images.githubusercontent.com/82012415/173126847-811d2637-7835-446e-ad67-a9e0cbaa937f.png)

**Steps to Reproduce**
1. Run the project on Chrome
2. Log in to the app and open the console.
3. Click the plus icon in the lower right corner
4. Fill out the form and click "confirm" button to add an expense to the app

Actual Behavior
When you follow the steps to reproduce, the error will appear in the console.

Expected Behavior
There should be no errors in the console

Troubleshooting/Testing Steps Attempted
None yet.

Workaround
None yet.

**Comment by alberme** [comment]
![image](https://user-images.githubusercontent.com/3313769/173126152-4071d024-f79c-47f6-941b-9ec71f598e8e.png)
