### ISSUE TITLE
Redesign "Extra Money" component

### ISSUE THREAD

**Issue by garanico** [luceroweb/karot-saving-smart#63]
[time box: 1-2 hours , complexity points:  1]

As a user, I want to see the new design of the "Extra Money" component predominantly on the screen so that when I select it, it will show my account sources which shows me where my money is coming from.

**User Expectations**
- The new design of the "Extra Money" component
- The new pull down tab
  - Displays the accounts list when selected

**Developer Dependencies**
Figma:  https://www.figma.com/file/qgAYJmI9jnoocgKRfWarpb/Envelope-App?node-id=1292%3A10885

- "Extra Money" Modal component:
![extra-money-component](https://user-images.githubusercontent.com/82012415/173448495-90be0910-0340-4658-8f74-32b0615ed2df.png)

- Extra Money Modal in Overview component:
![extra-money-component-overview](https://user-images.githubusercontent.com/82012415/173448575-89dd49d5-66c4-4c62-b58b-fe1d7cb60220.png)

- Google Font: Sarabun: https://www.npmjs.com/package/@expo-google-fonts/sarabun
- #6

**Comment by luceroweb** [comment]
@garanico @alberme hold this issue pending the design refactor tickets that are coming soon to accommodate new design changes in Figma.

**Comment by luceroweb** [comment]
@garanico I updated this description slightly to focus on the redesigned UI
