### ISSUE TITLE
Bug: Splash screen white flicker

### ISSUE THREAD

**Issue by garanico** [luceroweb/karot-saving-smart#64]
**Date Seen**
6/7/22

**Versions**
iOS
Android
Develop branch

**Bug Description**
When the app first loads up, a white background will flicker or flash for a quick moment before rendering the login animation.

**Steps to Reproduce**
1. Run the app on iOS or Android
2. Observe a quick white flicker between the splash screen and the login screen

**Actual Behavior**
A white background flickers for a quick moment between the splash screen and login screen.

**Expected Behavior**
There should be no flicker or any other disruption when loading or transitioning been screens

**Troubleshooting/Testing Steps Attempted**
Not yet

**Workaround**
Not yet

**Comment by luceroweb** [comment]
@garanico @alberme this could be because we have a mostly blank splash screen image in our current expo assets folder.
