### ISSUE TITLE
Add UUID to Account Modal to Update Edit

### ISSUE THREAD

**Issue by darlanebrown** [luceroweb/karot-saving-smart#78]
[Timebox: 5 hours, Complexity: 3]

As a user, When I make an edit to an account, I don't want my account order to change, so that I'm not confused by a change in my account order.

As a Developer, I want an account UUID to make it easier to edit a specific account, and an order number so that I can display accounts in the order specified.

**User Expectations:**
- To edit an account 
- The accounts will not change sort order when an edit is made
- New accounts will display at the top of the list of accounts

**Developer Dependencies:**
- Install UUID package using npm https://www.npmjs.com/package/uuid
- Add `uuid: string;` & `sortOrder: number;` to `AccountType` in `Utils/types.tsx`
- Modify `AccountModal`
  - Get accounts list from Redux state
  - import UUID component (version 4)
  - Add `uuid: uuidv4()` & `sortOrder: accounts.length` to `newAccount` object definition in `runAddAccount` helper function
  - Change `runEditAccount` helper function to modify account by uuid instead of the current method of spreading the `unselectedAccounts` in with the `accountUpdate` value (you may need to change the `editAccount` reducer/action in `Utils/accountSlice.ts`
- Modify `AccountsDropDown.tsx`
  - Sort the `listOfAccounts` array in descending order using the `sortOrder` value (ex `listOfAccounts.sort((a, b) => (a.sortOrder < b.sortOrder) ? 1 : -1)`
  - In the `generateList` helper function, update the key to use `key={item.sortOrder}`

**Comment by luceroweb** [comment]
@darlanebrown I'm not sure how you did the uuid, but I added some notes about the sort order to this ticket that might help. If not, please modify the ticket. I've moved this ticket to the Accepted column.
