### ISSUE TITLE
Bug: Amount Placeholder and Add Button width when AccountModal is in "add" mode

### ISSUE THREAD

**Issue by srosenberg74** [luceroweb/karot-saving-smart#80]
**Date Seen**
6/14/22

**Versions**
Android Emulator
iOS
Chrome
develop branch

**Bug Description**
When using the AccountModal in "add" mode, the placeholder text for "amount" is not shown, and the Add button width is incorrect. 

![addaccountbug](https://user-images.githubusercontent.com/91571340/173702660-4f79f54f-ed82-4fa3-a449-fda7edd74612.png)

**Steps to Reproduce**
1. Start app
2. Login
3. Click the chevron to open the accounts drop down
4. Click on the plus sign above the "Balance/Extra Money" to add an account
5. Notice that, when the modal opens, there is already a 0 in the amount input, rather than the placeholder text "amount"
6. Notice that, on web, the Add Account button is not wide enough to hold the text, and the word Add appears inside the button and the word Account appears below it.

**Actual Behavior**
"0" is already loaded into the amount position, rather than the placeholder text "amount", and the Add Account button is not large enough to hold all of it's text.

**Expected Behavior**
The placeholder text "amount" should be in the amount input until the user enters an amount.  The Add Account button should be wide enough to hold the text "Add Account".

**Troubleshooting/Testing Steps Attempted**
None yet

**Workaround**
As @darlanebrown suggested, deleting the width and height for the `addButton` style appears to solve the Add Account button text problem.
Adding a conditional to the value property of the TextInput for the amount seems to solve the placeholder text issue: `value={mode !== "add" ? amount?.toString() : undefined}`

**Comment by luceroweb** [comment]
@srosenberg74 I don't have any changes to make to this bug ticket. It is ready to be worked. I've moved this ticket to the Accepted column, and assigned it to you.
