### ISSUE TITLE
Redesign Expense Card Component

### ISSUE THREAD

**Issue by xmercado** [luceroweb/karot-saving-smart#81]
[time box: 1-2 hours , complexity points:  1]

As a user, I want to see the new Expense Card component design in the app, so that it will contribute to a unified look & feel of the overall app.

**User Expectations**
- See newly designed Expense Card component
- Progress bar with money amounts (saved and goal)
- Text below progress bar that reads `${saved} of ${goal}`

**Developer Dependencies**
- Figma:  https://www.figma.com/file/qgAYJmI9jnoocgKRfWarpb/Envelope-App?node-id=1292%3A10885
- Expense Card Component
- Progress Bar: https://www.npmjs.com/package/react-native-progress
- Sarabun Google Font: https://www.npmjs.com/package/@expo-google-fonts/sarabun

**Comment by luceroweb** [comment]
@xmercado I updated the user story to reflect the design changes from the user's perspective. Please remember when you create a ticket, it should remain in the "Pending" column until a reviewer has accepted it and moved it into the "Accepted" column for you.
