### ISSUE TITLE
Bug: Account values are being concatenated together as strings rather than being added together as numbers

### ISSUE THREAD

**Issue by srosenberg74** [luceroweb/karot-saving-smart#82]
**Date Seen**
6/14/22

**Versions**
Android emulator
iOS 
Chrome
develop branch

**Bug Description**
The account amounts appear to be being concatenated together as a string rather than being added together as numbers.

![accountbug](https://user-images.githubusercontent.com/91571340/173706067-069e066e-a4c6-400c-81e5-e9d67a33b7ab.png)

**Steps to Reproduce**
1. Start the app
2. Login
3. Click on the AccountsDropDown chevron
4. Click on the plus sign below "Income"
5. Add an account with an amount value and label, then click "Add Account"
6. Click on the plus sign again to add another account
7. Add another account with an amount value and label, then click "Add Account"
8. Observe that the values of the account appear side by side for the "Balance/Extra Money" values, rather than being added together as numbers

**Actual Behavior**
The account values for multiple new accounts appear to be being concatenated as strings.

**Expected Behavior**
The account values should be added together as Numbers.

**Troubleshooting/Testing Steps Attempted**
None yet

**Workaround**
none yet

**Comment by luceroweb** [comment]
@srosenberg74 this bug ticket looks good without the need for any changes. I accepted this ticket and assigned it to you.
